# Generated by Django 3.2.7 on 2021-11-01 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='addtocarts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=64)),
                ('price2', models.IntegerField()),
                ('Total', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Total', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('Countrys', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Productmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('smalldesc', models.CharField(default='wonder-ful cloth', max_length=20)),
                ('desc', models.CharField(max_length=60)),
                ('desc1', models.CharField(blank=True, max_length=60)),
                ('desc2', models.CharField(blank=True, max_length=60)),
                ('desc3', models.CharField(blank=True, max_length=60)),
                ('desc4', models.CharField(blank=True, max_length=60)),
                ('desc5', models.CharField(blank=True, max_length=60)),
                ('desc6', models.CharField(blank=True, max_length=60)),
                ('desc7', models.CharField(blank=True, max_length=60)),
                ('desc8', models.CharField(blank=True, max_length=60)),
                ('desc9', models.CharField(blank=True, max_length=60)),
                ('price', models.IntegerField()),
                ('image2', models.ImageField(default='image.png', upload_to='')),
                ('image3', models.ImageField(default='image.png', upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('Type', models.CharField(choices=[('c', 'Coat'), ('j', 'Jacket'), ('b', 'Balzer'), ('o', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('user_name', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('Phone', models.IntegerField()),
                ('password', models.CharField(max_length=14)),
                ('Password2', models.CharField(max_length=14)),
                ('active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('Thecountry', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Homepage.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='cartorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.cart')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.productmen'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='addtocarts1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('items', models.ManyToManyField(to='Homepage.addtocarts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
