# Generated by Django 3.2.7 on 2021-11-01 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addtocarts2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=64)),
                ('price2', models.IntegerField()),
                ('Total', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='addtocarts1',
        ),
    ]
