# Generated by Django 3.2.7 on 2021-11-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_auto_20211101_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocarts2',
            name='image',
        ),
    ]
