# Generated by Django 3.2.7 on 2021-11-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_remove_addtocarts2_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocarts2',
            name='order',
            field=models.ManyToManyField(blank=True, to='Homepage.Productmen'),
        ),
    ]
