# Generated by Django 3.2.7 on 2021-11-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_alter_addtocarts2_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocarts2',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
