# Generated by Django 3.2.7 on 2021-11-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_alter_addtocarts_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
