# Generated by Django 3.2.7 on 2021-11-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0009_auto_20211102_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Total',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
