# Generated by Django 3.2.7 on 2021-11-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0010_alter_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocarts2',
            name='Total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
