# Generated by Django 3.2.7 on 2021-11-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0011_auto_20211103_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocarts2',
            name='Total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
