# Generated by Django 3.2.7 on 2021-11-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0012_auto_20211103_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
