# Generated by Django 3.2.7 on 2021-11-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0013_alter_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productwomen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('smalldesc', models.CharField(default='wonder-ful cloth', max_length=20)),
                ('desc', models.CharField(max_length=60)),
                ('desc1', models.CharField(blank=True, max_length=60)),
                ('desc2', models.CharField(blank=True, max_length=60)),
                ('desc3', models.CharField(blank=True, max_length=60)),
                ('desc4', models.CharField(blank=True, max_length=60)),
                ('desc5', models.CharField(blank=True, max_length=60)),
                ('desc6', models.CharField(blank=True, max_length=60)),
                ('desc7', models.CharField(blank=True, max_length=60)),
                ('desc8', models.CharField(blank=True, max_length=60)),
                ('desc9', models.CharField(blank=True, max_length=60)),
                ('price', models.IntegerField()),
                ('image2', models.ImageField(default='image.png', upload_to='')),
                ('image3', models.ImageField(default='image.png', upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('Type', models.CharField(choices=[('c', 'Coat'), ('j', 'Jacket'), ('b', 'jambsoat'), ('o', 'badboy'), ('d', 'dress'), ('a', 'accsesoris'), ('s', 'other')], max_length=1)),
            ],
        ),
    ]
